repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8  # Te sugiero usar "v" y ejecutar pre-commit autoupdate luego
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        exclude: ^tests/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.1
    hooks:
      - id: mypy
